package:
  name: biomechzoo
  version: "0.1.0"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"


requirements:
  host:
    - python >=3.10
    - pip
    - numpy
    - scipy
    - matplotlib
    - pandas
    - ezc3d
  run:
    - python >=3.10
    - numpy
    - scipy
    - matplotlib
    - pandas
    - ezc3d

about:
  home: https://github.com/mcgillmotionlab/biomechzoo
  license: MIT
  summary: "Biomechanical data processing toolkit"
